apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: event-greeter-build
spec:
  serviceAccountName: build-bot
  source:
    git:
      revision: $sourceRevision
      url: $sourceRepoUrl
  steps:
    - args:
        - "/usr/local/bin/buildah.sh"
      env:
        - name: WORK_DIR
          value: /workspace/$contextDir
        - name: DESTINATION_NAME
          value: $destinationImageName
        # uncomment this if you have MAVEN_MIRROR thats is reachable from your kube cluster
        # speeds up the builds - the example below uses Nexus repo manager installed in host machine
        # - name: MAVEN_MIRROR_URL
        #  value: $http://192.168.64.1:8081/nexus/content/groups/public
      image: quay.io/rhdevelopers/quarkus-java-builder
      name: build-and-push
      # needed for buildah builds to be running as containers
      securityContext:
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
        - mountPath: /root/.m2
          name: m2-cache
        - mountPath: /var/lib/containers
          name: container-storage
      workingDir: /workspace/$contextDir
  timeout: 60m
  volumes:
    - name: m2-cache
      persistentVolumeClaim:
        claimName: m2-cache
    - name: container-storage
      hostPath:
        path: /var/lib/containers
